### ISSUE TITLE
How to build on Linux?

### ISSUE THREAD

**Issue by probonopd** [BobanSpasic/MiniDexedLibrarian#2]
Hello @BobanSpasic, great work! I'd like to try it out but I am not running Windows. Do you know how to build this on Linux?

**Comment by BobanSpasic** [comment]
Hi @probonopd,

the current code relies on Windows Multimedia API for MIDI.
It'll take some time to write a cross-platform MIDI lib for FreePascal.

**Comment by BobanSpasic** [comment]
I got a working MIDI Out on Linux. I've compiled the interface for GTK2 and I can possibly compile it for QT5. I need to do some testing, to see if everything is working like it should.
I also need to figure out how to build DEB-packages (I am working on Linux Mint).

**Comment by probonopd** [comment]
That's great to hear. Do you have instructions I could follow on FreeBSD?

**Comment by BobanSpasic** [comment]
I fear I can't help there, except to set up a VM with FreeBSD myself and try to build the app.
My plans are to build it for Mac too, but my original plan was to have it feature-complete on one platform, and port it to other platforms after that.
I did it for Linux because I want to get involved in development of MiniDexed, so I needed a Linux VM anyway. I really want to get Performances sent over MIDI or over the network, and it seems that the only way to have it is to implement it by my self.

**Comment by BobanSpasic** [comment]
@probonopd 
Could you test the DEB files from the BIN folder?

**Comment by probonopd** [comment]
Do you have build instructions for how to build it from source? I'd like to try it on FreeBSD.

**Comment by BobanSpasic** [comment]
@probonopd 
I've compiled a FreeBSD 13 Qt5 executable. Same dependencies as for Linux (sqlite3, portmidi, Qt5Pas).
On my VM, I can't get any MIDI port listed. Could you check it?
Is this a good way to distribute a FreeBSD executable, or I need to pack it somehow before uploading? I can guess that the file attributes are got lost.

**Comment by probonopd** [comment]
Thank you very much for your efforts @BobanSpasic. I'm happy to test it. Is it available for download?

MIDI on FreeBSD is unfortunately a bit tricky; I wrote my collected insights on this topic over at https://hellosystem.github.io/docs/developer/midi.html. Let me see if I can get it to work...

**Comment by BobanSpasic** [comment]
All the binaries are here in repository, in bin folder. Just set the executable attribute after downloading.

**Comment by probonopd** [comment]
Tested. Working well, including MIDI. Thank you very much! :+1:
